### ISSUE TITLE
Discussion: Onboarding 

### ISSUE THREAD

**Issue by Frijol** [nodeconf/Adventure-UNCONF#19]
cc/ @fishrock123 @trott @qard @whyisjake @julianduque @dshaw @bryan-m-hughes @chrisdickinson @devinivy @dtex

Pulled out the action items:
- [ ] Add explicit call to action at the top of the main io.js repo for "get involved!"
- [ ] Make a quick start/start here section in the contribution guide: basic notes, link to "good for newbies" issue label, tell you to sign up for a mentor (and how to do this)
- [ ] Accessible communication channels. I think this ended up as: get Slack, hook up automatic cross-posting for IRC and/or Gitter if that's appropriate
- [ ] Review contributing documentation & fix so there's not as much assumed knowledge. (This would be a _great_ place to bring in people from the diversity discussion & have them help identify barriers to entry)
- [ ] Set up mentoring/make it better. See the notes, there was a lot of discussion here.

Full notes:
- Contributing.md - add explicit call to action at the top "Get involved!"
- Contributors guide is verbose, hard to get started with. Can there be a "start here" section with just the basics, try a bug from the newbies label, here's where to get help
- IRC/Gitter/Slack? IRC hard to get into, Gitter not great either. Connect IRC to slack – ask github.com/tcr
- Wordpress has a good manual/book
- Documentation should not have as much _assumed knowledge_
- Find Slack channels associated with the topic you want to contribute to
- This is the barrier to entry – foster communication with the Diversity discussion to improve the onboarding process accordingly
- Mentors assigned to newbies – would you want one, would you volunteer for it?
  - Yes, would do it for someone else
    - but would I be valuable? Core people would be more useful.
      - Does that mean you're just not onboarded enough?
      - Mentorship useful even if you just know who to tell them to talk to
    - Rockstars are great & friendly people & people are still intimidating
  - Mentor would learn a lot by mentoring
  - Doesn't have to be centrally blessed; rogue mentoring is cool, might not get everyone
  - The more we have mentoring, the better our bus factor – spread the knowledge
  - It's already documented who owns parts of the system, but you might not know what you don't know and that's what a mentor is for - get you some context
  - The act of setting up as a mentor means you are likely to improve the quality of information sharing we do overall.
  - Could have just read the onboarding docs in person, but wouldn't have learned nearly as much as sitting down with the mentor
  - Implementation needs thought: how do you get a mentor?
    - "Ask if you have questions" isn't good enough. Feels like asking a favor, intimidating. Mentor instead needs to schedule a 1:1 in the future "we'll talk, and see if I can help you with anything"
  - Precedent for mentorship with Hapi - talk to Eran Hammer
    - You could be a mentor + a mentee simultaneously in that program based on your different areas of expertise – topic-based mentorship
      - Inter-working group communication is currently not good, this could help
- Useful to have multiple formats. Video work for some, not others
  - Jeremiah has some plans for this

**Comment by Trott** [comment]
Thanks, @Frijol and @dshaw for taking all the great notes!

What should we do with the action items? Adopt/assign them amongst ourselves? Try to identify champions and open tickets in the right repos?

**Comment by chrisdickinson** [comment]
Hey! Sorry I wasn't able to make it to this session – I got waylaid by the streams discussion. [Here's](https://gist.github.com/chrisdickinson/b7ec569f1d5fe7104391) the document I use for onboarding existing collaborators. It's changed over time – removing deep dives on code in favor of brevity, for example. I note this, because [I've collected responses](https://docs.google.com/spreadsheets/d/1cde71AaQHP8vk8ns4sj8SLM6RZWqwE0TJZbkzFrB-tA/edit?usp=sharing) to a (rough) post-onboarding survey. 

Some notes about the past onboardings: I've done them in private hangouts thus far in an effort to reduce stress for those being onboarded, and to encourage folks to ask questions / speak up.

Re: docs – the results of the documentation IA workshop are [here](https://github.com/nodejs/docs/issues) – in the form of a new WG – if anyone would like to get involved! We made a space for onboarding input on the collaborator / internal docs inside the project metadata section. The concerns about assumed knowledge were echoed in the docs WG – we're hoping to address this with a lead-in tutorial section, as well as topic guides with associated "difficulty levels."

Something like a slack channel, discourse forum, even a github repo for conversations between collaborators would make me a lot happier with the onboarding process – many of the collaborators don't really hear from each other after the fact with the exception of the issue tracker, which isn't a great space for them to interact and form a community.

**Comment by Trott** [comment]
The "add explicit call to action" suggestion was modeled on another community. Does anyone remember what community it was? Was it hapijs and the way they have "Contribute" in the top nav linking to http://hapijs.com/contribute? Or was it something else?

**Comment by dtex** [comment]
I had mentioned that I like the way the hapi.js team surfaces beginner issues to the Contributing page and I remember mention of an explicit CTA in the docs discussion earlier, but I don't remember mention of a CTA in this discussion (but then I forget lots of things).
