### ISSUE TITLE
Alcohol Procurement & Suggestions

### ISSUE THREAD

**Issue by ryan-sandy** [nodeconf/Adventure-UNCONF#27]
In past nodeconfs we drank through almost all the cases of beer. One option we could explore is getting kegs of beer. We could potentially have our beer catered by a brewery. Lagunitas is down the road and has an [event contact form](https://lagunitas.com/donations/off-site).

However we would need to check with Walter Creek Ranch if they allow kegs and if they allow outside catering of alcohol.

**Comment by mikeal** [comment]
The main reason we went with bottles instead of kegs was to ensure a variety. In the early days it was also for ease of transport, we would move the beer to where people were, but we've had much better luck moderating alcohol usage with keeping a set "bar area."

Also, we've done things differently each year. When attendance was a lot higher we would have Bevmo deliver all the beer because it was too much work to do a run. This year, and in the earlier years, when attendance was lower did a few different trips to the store. The years that we did the delivery we definitely over ordered and ended up leaving the camp staff with a ton of beer :)

**Comment by mikeal** [comment]
Oh, also, the spirits and wine is a pretty complicated story with big purchases in some years and a lot of it carried year over year. Not to mention me barrel aging cocktails for the last few.

**Comment by tamzinblake** [comment]
So after talking on slack and offline, we've pretty much sorted this one.
1. We don't want to heavily promote that this event will feature alcohol, so sponsorship from a brewery is straight out
2. We probably don't want free access to liquor (this was mentioned this year too) so the bar will be open at particular times with a volunteer bartender/server (@xablake has volunteered to be the default if nobody else wants to do it).
3. Nobody needs 13 varieties of gin.  We'll pre-mix some cocktails and bring some well liquor (including vodka) for mixers, and maybe have a few of our fine liquors if they'll last another year.
4. We're going to have a bunch of signature non-alcoholic drinks and promote those much more prominently than the alcohol.
5. We'll figure out the beer situation. Probably not kegs since it strangely encourages overconsumption and variety is better.
